title: Custom Domains for Anything
description: Using cloudflared and a free domain service you can generate custom domains for any one of your projects!
theme: just-the-docs

url: https://custom-domains-for-anything.github.io

plugins:
  - jekyll-default-layout

color_scheme: light
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  example: 
    title: Example
    color: green



